### ISSUE TITLE
[BUG] Jetpack Compose doesn't show "Cursor handle" when inputting text

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#160]

**Comment by ILIYANGERMANOV** [comment]
Jetpack Compose Input field doesn't support Cursor handler, yet :/ If someone knows how to fix/workaround that I'd be extremely grateful!

**Comment by MohitMandalia** [comment]
I would like to check on it if i can find some workaround so basically when we enter amount there is no cursor is that the issue here?

**Comment by ILIYANGERMANOV** [comment]
Hi @MohitMandalia the issue is that the Title & Description input fields doesn't have a cursor handle because the new jetpack compose input fields doesn't support it.
 
What I did as workaround is to use ported EditText but that has different issues. Feel free to try finding a workaround on this :) It'll be major improvement!

**Comment by MohitMandalia** [comment]
sure will try to come up with some workaround if I can.
Thanks for the explanation.

**Comment by MohitMandalia** [comment]
Can I get a context on where exactly this issue exist I am new to compose and tried to use BasicTextField in other project  and has a blinking cursor handle could you please guide me with the problem so I can look for some alternative.

**Comment by ILIYANGERMANOV** [comment]
Great question! I just checked it out and it was fixed by the latest Jetpack Compose update!! Amazing 🚀

**Comment by MohitMandalia** [comment]
okk cool.

No worries.
