### ISSUE TITLE
[BUG] Transactions may appear in a wrong date because UTC <-> Local time differences

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#174]
**Describe the bug**

**To Reproduce**
1. Add transaction in 1 am GMT+3, 28 Nov
2. Go to transaction history
3. It'll appear in 27 Nov

**Solution**
Group transactions by date based on local time, not UTC.

**Comment by Vishwa-Raghavendra** [comment]
I don't think this bug is related to Grouping of transactions ,
The transactions are stored wi



th time in UTC format in DB and displayed as LocalTime in HomeTabScreen

The issue is with the date/time picker 

https://user-images.githubusercontent.com/42895647/146583311-5173c8a0-fd9f-4de1-9ba6-6dfcd15b963d.mp4

I live in a location with GMT + 5 Hrs 30 mins

Unless I select the transaction time to be greater than GMT time the reported time is wrong

eg:
In the above video if i select the time to be DEC 16th 1 am since the "time" selected is less than 5 hours from 12 am clock it reports wrong dateTime 

if I select  DEC 16 th 5 pm since the time selected is greater than 5 hours from 12 am then the date is reported correctly

**Comment by Vishwa-Raghavendra** [comment]
Related to #357
