### ISSUE TITLE
Question: Why `LiveData` over `StateFlow`? 

### ISSUE THREAD

**Issue by quebin31** [ILIYANGERMANOV/ivy-wallet#66]
**Is the project building?**
Yes

**What would you like to improve?**
Replace `LiveData` with Kotlin's `Flow` interface, `StateFlow` for UI 

Because:
`Flow`s are officially supported by Jetpack Compose and it's Kotlin native with a more versed and complete API than LiveData.

**Comment by ILIYANGERMANOV** [comment]
Hi @quebin31, thank you for forking our project and opening this discussion!

**Reasons behind using `LiveData`**
- Wasn't aware of `StateFlow` when starting the project
- `LiveData` works well for Ivy Wallet's use case
- `LiveData` is lifecycle aware which turns out to be "manually lifecycle-aware" when using Jetpack Compose

```kotlin
@Composable
fun <R, T : R> LiveData<T>.observeAsState(initial: R): State<R> {
    val lifecycleOwner = LocalLifecycleOwner.current
    val state = remember { mutableStateOf(initial) }
    DisposableEffect(this, lifecycleOwner) {
        val observer = Observer<T> { state.value = it }
        observe(lifecycleOwner, observer)
        onDispose { removeObserver(observer) }
    }
    return state
}
```

**What would be the main benefits in migrating the project to the `Flow` API?**
- a
- b
- c

**Can you give me practical code examples of these benefits?**
Paste Kotlin code below.

Btw, I'm open to migrating to the `State` API but first I want to know the WHY (the motivation behind it) and second if we start we should start small. Let's say submit PR for one screen only so we can test the implications and if it's good - roll over the entire app.

**Comment by ILIYANGERMANOV** [comment]
Hi again @quebin31, I had a look at Kotlin's `Flow` API and I agree with you. It's a better choice than `LiveData`. Are you interested in working on this issue yourself?

If so, just let me know and I'll assign you to it.

**Comment by ILIYANGERMANOV** [comment]
@quebin31 I'll take that migration. The `Flow` API will benefit us a lot. Thanks for the suggestion!

**Comment by ILIYANGERMANOV** [comment]
We've started the migration and it's already happening => I'll close this ticket.
